import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Notification } from "@/components/ui/Notification";
import DarkModeButton from "@/components/DarkModeButton";
import NavBar from "@/components/NavBar";
import UserProvider from "@lib/userProvider";
import { getUserProfileFromDb } from "@lib/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn("layout", "min-h-dvh", "", "")}
    >
      <head>
        <title>2Do app</title>
      </head>
      <body
        className={cn(
          "relative",
          "flex",
          "flex-col",
          "min-h-dvh",
          "w-full",
          "m-0",
          "gap-0",
          "items-center",
          "mb-10",
          "",
          "",
        )}
      >
        <UserProvider>
          <header className={cn("w-screen", "", "")}>
            <nav>
              <NavBar />
            </nav>
          </header>
          <main
            className={cn(
              "flex-1",
              "grid",
              "gap-5",
              "items-center",
              "content-center",
              "",
              "",
            )}
          >
            <Notification
              message="There is a known vulnerability in a dependency. Please be cautious."
              storageKey="warning:dependency-v20260108"
              moreUrl="https://github.com/advisories/GHSA-8r9q-7v3j-jr4g"
              moreTitle="Anthropic's MCP TypeScript SDK has a ReDoS vulnerability"
              moreText={`@modelcontextprotocol/sdk  <1.25.2
                    Severity: high
                    Anthropic's MCP TypeScript SDK has a ReDoS vulnerability - https://github.com/advisories/GHSA-8r9q-7v3j-jr4g
                    No fix available
                    node_modules/@modelcontextprotocol/sdk
                    next-devtools-mcp  *
                    Depends on vulnerable versions of @modelcontextprotocol/sdk
                    Depends on vulnerable versions of undici
                    node_modules/next-devtools-mcp`}
              type="warning"
            />
            {children}
            <DarkModeButton />
          </main>

          <footer></footer>
        </UserProvider>
      </body>
    </html>
  );
}
