import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Warning } from "@/components/ui/Warning";
import DarkModeButton from "@/components/DarkModeButton";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					`overflow-y-scroll  font-sans ${geistSans.variable} ${geistMono.variable} antialiased`,
					"grid",
					"grid-cols-1",
					"grid-rows-auto",
					"gap-10",
					"max-w-4xl",
					"lg:p-10", //implied p-0 for mobile
					"mt-10 mb-20",
					"justify-self-center",
					"",
					""
				)}
			>
				<DarkModeButton />
				<Warning
					message="There is a known vulnerability in a dependency. Please be cautious."
					storageKey="warning:dependency-v20260108"
					moreUrl="https://github.com/advisories/GHSA-8r9q-7v3j-jr4g"
				/>

				{children}
			</body>
		</html>
	);
}
